# Generated by Django 3.2.15 on 2023-06-20 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Введите корректное значение поля "username"', regex='^[\\w.@+-]+\\Z')], verbose_name='Ник пользователя'),
        ),
    ]
